[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.19"

[rpc_endpoints]
goerli = "${FOUNDRY_ETH_RPC_URL}"
goerli_base = "${GOERLI_BASE_RPC_URL}"
linea = "${LINEA_RPC_URL}"
celo = "${CELO_TESTNET_RPC_URL}"
scroll = "${SCROLL_TESTNET_RPC_URL}"
mantle = "${MANTLE_TESTNET_RPC_URL}"
zksync = "${ZKSYNC_TESTNET_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
arbitrum_sepolia = "${ARBITRUM_SEPOLIA_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
